### PR TITLE
Add code of conduct and contributor guidelines

### PR DESCRIPTION
**Pull request by jreut**

### CODE REVIEW

**Comment by jreut** [comment]
Hey @bittelc, what do you think about this?

**Comment by bittelc** [comment]
I think you copied and pasted it from a Google search "code of conduct for developers". But that's cool.
I like the idea of fostering and accepting and welcoming and contributing...

Below, you can find my hand-checked checkbox.

- [x]

**Comment by jreut** [comment]
Yeah, I shopped around for a code of conduct that was the best bit. Just wanted to give you a heads up given you're the one and only contributor for now.

**Comment by jreut** [comment]
I forgot to mention how sweet that checkbox is.

**Comment by bittelc** [comment]
That's about to change. This repo's about to blow up with contributors. :boom:

- [x]

**Comment by jreut** [comment]
- [ ] checkboxes on
- [ ] checkboxes on
- [ ] checkboxes

**Pull request merged**
